"""
Comprehensive test suite for metadata inspector and cleaner.
"""
import os
import io
import shutil
import tempfile
import struct
import unittest
from PIL import Image, PngImagePlugin

from core.inspector import inspect_image_metadata
from core.cleaner import (
    strip_jpeg_lossless,
    strip_png_lossless,
    clean_single_image,
    process_directory
)


class TestMetadataCleaner(unittest.TestCase):

    def setUp(self):
        self.test_dir = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.test_dir, ignore_errors=True)

    def test_png_prompt_stripping(self):
        """Test stripping text chunks and prompts from PNG."""
        png_path = os.path.join(self.test_dir, "test_ai.png")
        im = Image.new("RGBA", (50, 50), color=(255, 100, 50, 255))
        meta = PngImagePlugin.PngInfo()
        meta.add_text("parameters", "masterpiece, 8k, photorealistic cat\nNegative prompt: blurry\nSteps: 20")
        meta.add_text("Software", "ChatGPT DALL-E 3")
        im.save(png_path, format="PNG", pnginfo=meta)

        # Inspect before
        info_before = inspect_image_metadata(png_path)
        self.assertTrue(info_before["has_ai_prompt"])
        self.assertIn("parameters", info_before["ai_prompts"])

        # Clean
        out_path = os.path.join(self.test_dir, "clean_ai.png")
        res = clean_single_image(png_path, out_path)
        self.assertTrue(res["success"])

        # Inspect after
        info_after = inspect_image_metadata(out_path)
        self.assertFalse(info_after["has_ai_prompt"])
        self.assertEqual(len(info_after["raw_text_chunks"]), 0)

        # Verify image integrity
        with Image.open(out_path) as check:
            self.assertEqual(check.size, (50, 50))
            self.assertEqual(check.mode, "RGBA")

    def test_jpeg_lossless_metadata_stripping(self):
        """Test stripping EXIF and comments from JPEG."""
        jpg_path = os.path.join(self.test_dir, "test_camera.jpg")
        im = Image.new("RGB", (60, 60), color=(100, 150, 200))
        # Add comment
        im.save(jpg_path, format="JPEG", quality=90, comment=b"Generated by AI Model v2.0")

        # Inject fake APP11 (C2PA) marker
        with open(jpg_path, "rb") as f:
            raw = f.read()
        fake_app11 = b"\xff\xeb\x00\x1cJUMBF/urn:c2pa:test-manifest"
        raw_with_c2pa = raw[:2] + fake_app11 + raw[2:]
        with open(jpg_path, "wb") as f:
            f.write(raw_with_c2pa)

        # Clean
        out_path = os.path.join(self.test_dir, "clean_camera.jpg")
        res = clean_single_image(jpg_path, out_path, mode="smart_lossless")
        self.assertTrue(res["success"])

        with open(out_path, "rb") as f:
            cleaned_bytes = f.read()

        # Ensure APP11 (FF EB) is completely gone
        self.assertNotIn(b"\xff\xeb", cleaned_bytes)
        self.assertNotIn(b"Generated by AI Model", cleaned_bytes)

        # Verify image opens perfectly
        with Image.open(out_path) as check:
            self.assertEqual(check.size, (60, 60))

    def test_directory_batch_processing(self):
        """Test batch processing of multiple folders with recursion."""
        sub_dir = os.path.join(self.test_dir, "subfolder")
        os.makedirs(sub_dir)

        # Create 3 images
        for i, folder in enumerate([self.test_dir, sub_dir, sub_dir]):
            path = os.path.join(folder, f"photo_{i}.png")
            im = Image.new("RGB", (30, 30), color="blue")
            im.save(path)

        output_dir = os.path.join(self.test_dir, "cleaned_output")
        stats = process_directory(
            input_dir=self.test_dir,
            output_dir=output_dir,
            recursive=True
        )

        self.assertEqual(stats["total_found"], 3)
        self.assertEqual(stats["success_count"], 3)
        self.assertEqual(stats["error_count"], 0)

    def test_png_to_jpg_conversion_and_overwrite(self):
        """Test that PNG is converted to JPG without overwriting original, while JPG is overwritten."""
        # 1. Test PNG in directory processing with overwrite=True
        png_path = os.path.join(self.test_dir, "graphic.png")
        im_png = Image.new("RGBA", (40, 40), color=(255, 0, 0, 128))
        im_png.save(png_path)

        jpg_path = os.path.join(self.test_dir, "photo.jpg")
        im_jpg = Image.new("RGB", (40, 40), color=(0, 255, 0))
        im_jpg.save(jpg_path)

        stats = process_directory(
            input_dir=self.test_dir,
            overwrite=True,
            make_backup=False,
            recursive=False
        )

        # PNG original must still exist
        self.assertTrue(os.path.exists(png_path))
        # New JPG created from PNG must exist
        expected_jpg = os.path.join(self.test_dir, "graphic.jpg")
        self.assertTrue(os.path.exists(expected_jpg))
        # Photo JPG must still exist (overwritten)
        self.assertTrue(os.path.exists(jpg_path))

        with Image.open(expected_jpg) as check:
            self.assertEqual(check.format, "JPEG")
            self.assertEqual(check.size, (40, 40))


if __name__ == "__main__":
    unittest.main()
